// client-react/pages/accounting/return.tsx
import Head from "next/head";
import {
  Button,
  Container,
  Grid,
  useMantineTheme,
  Text,
  Stack,
  ThemeIcon,
  Title,
  Center,
} from "@mantine/core";
import { EntityTable } from "root/components/EntityTable";
import { ReturnMetadata } from "root/models/Return";
import { IconChevronLeft, IconReceiptRefund } from "@tabler/icons-react";
import Link from "next/link";
import { ReturnItemMetadata } from "root/models/ReturnItem";
import { useState } from "react";
import { useReturnAccounting } from "root/hooks/useAccounting";

export default function ReturnAccounting() {
  const theme = useMantineTheme();
  const [selected, setSelected] = useState<number | undefined>(undefined);
  const deleteDebtReturn = useReturnAccounting();
  return (
    <>
      <Head>
        <title>Повернення</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12}>
            <Center>
              <Link href="/accounting">
                <Button variant="subtle" pl="xs" pr="lg">
                  <IconChevronLeft />
                  Назад
                </Button>
              </Link>
            </Center>
          </Grid.Col>
          <Grid.Col span={12}>
            <Stack align="center">
              <Title align="center">
                <ThemeIcon size={34} variant="default" radius="md">
                  <IconReceiptRefund color={theme.fn.primaryColor()} />
                </ThemeIcon>
                &nbsp;&nbsp;Повернення
              </Title>
              <Text>Реєстрація повернення кошику з друком</Text>
            </Stack>
          </Grid.Col>
          <Grid.Col lg={6} span={12}>
            <EntityTable
              metadata={ReturnMetadata}
              untitled={false}
              controlled={undefined}
              singular={{ val: selected, set: setSelected, mod: false }}
              crudEnabled={true}
            />
          </Grid.Col>
          <Grid.Col lg={6} span={12}>
            <Stack>
              <EntityTable
                metadata={ReturnItemMetadata}
                untitled={false}
                controlled={[{ column: "ReturnId", value: selected }]}
                singular={undefined}
                crudEnabled={true}
              />
              <Button
                disabled={!selected}
                variant="light"
                onClick={() => selected && deleteDebtReturn(selected)}
              >
                Списати борг
              </Button>
            </Stack>
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}

// client-solid/src/routes/accounting/return.tsx
import { createEffect, createSignal, on } from "solid-js";
import { EntityTable } from "~/components/EntityTable";
import { GenericDBEntityPage } from "~/components/GenericDBEntityPage";
import { useReturnAccounting } from "~/hooks/useAccounting";
import { ReturnMetadata } from "~/models/Return";
import { ReturnItemMetadata } from "~/models/ReturnItem";
import { Button } from "~/ui/components/Button";

const control = (val: number | undefined) => ({
  column: "ReturnId",
  value: val,
});

export default function ReturnAccounting() {
  const [selected, setSelected] = createSignal<number | undefined>(undefined);
  const [controlled, setControlled] = createSignal<
    { column: string; value: number | undefined }[]
  >([control(selected())]);
  const deleteDebtReturn = useReturnAccounting();

  createEffect(on(selected, () => setControlled([control(selected())])));

  return (
    <GenericDBEntityPage
      prevRoute="/accounting"
      icon="i-tabler-receipt-refund"
      title="Повернення"
      heading="Повернення"
      description="Реєстрація повернення кошику з друком"
    >
      <div class="grid grid-cols-12 gap-3 items-start">
        <div class="col-span-12 xl:col-span-6 flex flex-col items-stretch justify-center gap-3">
          <EntityTable
            metadata={ReturnMetadata}
            singular={{ get: selected, set: setSelected }}
            create
            edit
            refresh
            delete
          />
          <Button
            attributes={{
              disabled: !selected(),
              onClick: () => selected() && deleteDebtReturn(selected()!),
            }}
            size="xl"
            variant="light"
          >
            Списати борг
          </Button>
        </div>
        <div class="col-span-12 xl:col-span-6">
          <EntityTable
            metadata={ReturnItemMetadata}
            controlled={controlled as any}
            create
            edit
            refresh
            delete
          />
        </div>
      </div>
    </GenericDBEntityPage>
  );
}
