// client-react/pages/management/index.tsx
import Head from "next/head";
import { Container, Grid, rem, Title } from "@mantine/core";
import { IconAddressBook } from "@tabler/icons-react";
import { DBEntityButton } from "root/components/Buttons/DBEntityButton";
import { UserMetadata } from "root/models/User";
import { UserClaimMetadata } from "root/models/UserClaim";
import { EnrollmentEventMetadata } from "root/models/EnrollmentEvent";
import { EnrollmentMetadata } from "root/models/Enrollment";

const HEIGHT_1 = rem(100);

export default function Management() {
  return (
    <>
      <Head>
        <title>Управління</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid justify="center">
          <Grid.Col span={12} my="xl">
            <Title order={1} align="center">
              Екран управління
            </Title>
          </Grid.Col>
          <Grid.Col lg={3} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={UserMetadata}
              height={HEIGHT_1}
              link="/management/user"
            />
          </Grid.Col>
          <Grid.Col lg={3} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={UserClaimMetadata}
              height={HEIGHT_1}
              link="/management/role"
            />
          </Grid.Col>
          <Grid.Col lg={3} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={EnrollmentEventMetadata}
              height={HEIGHT_1}
              link="/management/event"
            />
          </Grid.Col>
          <Grid.Col lg={3} sm={6}>
            <DBEntityButton
              Icon={<IconAddressBook size="2.375rem" />}
              metadata={EnrollmentMetadata}
              height={HEIGHT_1}
              link="/management/enrollment"
            />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}

// client-solid/src/routes/management/index.tsx
import { For } from "solid-js";
import { Title } from "solid-start";
import { EntityButton } from "~/components/EntityButton";
import { EnrollmentMetadata } from "~/models/Enrollment";
import { EnrollmentEventMetadata } from "~/models/EnrollmentEvent";
import { UserMetadata } from "~/models/User";
import { UserClaimMetadata } from "~/models/UserClaim";
import { Text } from "~/ui/components/Text";

const managementEntities = [
  {
    icon: undefined,
    metadata: UserMetadata,
    href: "/management/user",
  },
  {
    icon: undefined,
    metadata: UserClaimMetadata,
    href: "/management/role",
  },
  {
    icon: undefined,
    metadata: EnrollmentEventMetadata,
    href: "/management/event",
  },
  {
    icon: "i-tabler-address-book",
    metadata: EnrollmentMetadata,
    href: "/management/enrollment",
  },
];

export default function Management() {
  return (
    <>
      <Title>Управління</Title>
      <main class="px-5 py-10 sm:py-20 flex flex-col items-center">
        <div class="max-w-4xl w-full grid grid-cols-12 justify-center justify-items-center content-center items-center place-content-center place-items-center gap-3">
          <Text class="col-span-12 my-10 text-4xl sm:text-6xl text-center font-semibold">
            Екран управління
          </Text>
          <For each={managementEntities}>
            {(entity) => (
              <EntityButton
                class="col-span-12 md:col-span-6"
                icon={entity.icon}
                metadata={entity.metadata}
                href={entity.href}
              />
            )}
          </For>
        </div>
      </main>
    </>
  );
}
