// client-solid/src/routes/accounting/bookcategory.tsx
import { createEffect, createSignal, on } from "solid-js";
import { EntityTable } from "~/components/EntityTable";
import { GenericDBEntityPage } from "~/components/GenericDBEntityPage";
import { BookMetadata } from "~/models/Book";
import { BookCategoryMetadata } from "~/models/BookCategory";

const control = (val: number | undefined) => ({
  column: "CategoryId",
  value: val,
});

export default function BookCategoryAccounting() {
  const [selected, setSelected] = createSignal<number | undefined>(undefined);
  const [controlled, setControlled] = createSignal<
    { column: string; value: number | undefined }[]
  >([control(selected())]);

  createEffect(on(selected, () => setControlled([control(selected())])));

  return (
    <GenericDBEntityPage
      prevRoute="/accounting"
      icon="i-tabler-category-2"
      title="Категорії книг"
      heading="Категорія книги"
      description="Список категорій друку для каталогізації та подальшого пошуку"
    >
      <div class="grid grid-cols-12 gap-3">
        <div class="col-span-12 xl:col-span-4">
          <EntityTable
            metadata={BookCategoryMetadata}
            singular={{ get: selected, set: setSelected }}
            create
            edit
            refresh
          />
        </div>
        <div class="col-span-12 xl:col-span-8">
          <EntityTable
            metadata={BookMetadata}
            controlled={controlled as any}
            create
            edit
            refresh
            delete
          />
        </div>
      </div>
    </GenericDBEntityPage>
  );
}

// client-react/pages/accounting/bookcategory.tsx
import Head from "next/head";
import {
  Button,
  Container,
  Grid,
  Stack,
  ThemeIcon,
  Title,
  Text,
  useMantineTheme,
  Center,
} from "@mantine/core";
import { EntityTable } from "root/components/EntityTable";
import { BookCategoryMetadata } from "root/models/BookCategory";
import { IconCategory2, IconChevronLeft } from "@tabler/icons-react";
import Link from "next/link";
import { useState } from "react";
import { BookMetadata } from "root/models/Book";

export default function BookCategoryAccounting() {
  const theme = useMantineTheme();
  const [selected, setSelected] = useState<number | undefined>(undefined);
  return (
    <>
      <Head>
        <title>Категорії книг</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12}>
            <Center>
              <Link href="/accounting">
                <Button variant="subtle" pl="xs" pr="lg">
                  <IconChevronLeft />
                  Назад
                </Button>
              </Link>
            </Center>
          </Grid.Col>
          <Grid.Col span={12}>
            <Stack align="center">
              <Title align="center">
                <ThemeIcon size={34} variant="default" radius="md">
                  <IconCategory2 color={theme.fn.primaryColor()} />
                </ThemeIcon>
                &nbsp;&nbsp;Категорія книги
              </Title>
              <Text>
                Список категорій друку для каталогізації та подальшого пошуку
              </Text>
            </Stack>
          </Grid.Col>
          <Grid.Col lg={6} span={12}>
            <EntityTable
              metadata={BookCategoryMetadata}
              untitled={false}
              controlled={undefined}
              singular={{ val: selected, set: setSelected, mod: false }}
              crudEnabled={true}
            />
          </Grid.Col>
          <Grid.Col lg={6} span={12}>
            <EntityTable
              metadata={BookMetadata}
              untitled={false}
              controlled={[{ column: "CategoryId", value: selected }]}
              singular={undefined}
              crudEnabled={true}
            />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}
