// client-solid/src/routes/accounting/index.tsx
import { For } from "solid-js";
import { Title } from "solid-start";
import { EntityButton } from "~/components/EntityButton";
import { BookMetadata } from "~/models/Book";
import { BookCategoryMetadata } from "~/models/BookCategory";
import { BorrowMetadata } from "~/models/Borrow";
import { ReturnMetadata } from "~/models/Return";
import { SupplierMetadata } from "~/models/Supplier";
import { SupplyMetadata } from "~/models/Supply";
import { Text } from "~/ui/components/Text";

const accountingEntities = [
  {
    icon: undefined,
    metadata: BookCategoryMetadata,
    href: "/accounting/bookcategory",
  },
  {
    icon: undefined,
    metadata: BookMetadata,
    href: "/accounting/book",
  },
  {
    icon: "i-tabler-receipt",
    metadata: BorrowMetadata,
    href: "/accounting/borrow",
  },
  {
    icon: "i-tabler-receipt-refund",
    metadata: ReturnMetadata,
    href: "/accounting/return",
  },
  {
    icon: undefined,
    metadata: SupplierMetadata,
    href: "/accounting/supplier",
  },
  {
    icon: "i-tabler-square-rounded-plus",
    metadata: SupplyMetadata,
    href: "/accounting/supply",
  },
];

export default function Accounting() {
  return (
    <>
      <Title>Облік</Title>
      <main class="px-5 py-10 sm:py-20 flex flex-col items-center">
        <div class="max-w-4xl w-full grid grid-cols-12 gap-3">
          <Text class="col-span-12 my-10 text-4xl sm:text-6xl text-center font-semibold">
            Екран обліку
          </Text>
          <For each={accountingEntities}>
            {(entity) => (
              <EntityButton
                class="col-span-12 md:col-span-6"
                icon={entity.icon}
                metadata={entity.metadata}
                href={entity.href}
              />
            )}
          </For>
        </div>
      </main>
    </>
  );
}

// client-react/pages/accounting/index.tsx
import Head from "next/head";
import { Container, Grid, rem, Title } from "@mantine/core";
import {
  IconReceipt,
  IconReceiptRefund,
  IconSquareRoundedPlus,
} from "@tabler/icons-react";
import { DBEntityButton } from "root/components/Buttons/DBEntityButton";
import { BookCategoryMetadata } from "root/models/BookCategory";
import { BookMetadata } from "root/models/Book";
import { BorrowMetadata } from "root/models/Borrow";
import { ReturnMetadata } from "root/models/Return";
import { SupplierMetadata } from "root/models/Supplier";
import { SupplyMetadata } from "root/models/Supply";

const HEIGHT_1 = rem(100);

export default function Accounting() {
  return (
    <>
      <Head>
        <title>Облік</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="xl" my="xl" p={0}>
        <Grid>
          <Grid.Col span={12} my="xl">
            <Title order={1} align="center">
              Екран обліку
            </Title>
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={BookCategoryMetadata}
              height={HEIGHT_1}
              link="/accounting/bookcategory"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={BookMetadata}
              height={HEIGHT_1}
              link="/accounting/book"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconReceipt size="2.375rem" />}
              metadata={BorrowMetadata}
              height={HEIGHT_1}
              link="/accounting/borrow"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconReceiptRefund size="2.375rem" />}
              metadata={ReturnMetadata}
              height={HEIGHT_1}
              link="/accounting/return"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={undefined}
              metadata={SupplierMetadata}
              height={HEIGHT_1}
              link="/accounting/supplier"
            />
          </Grid.Col>
          <Grid.Col lg={4} sm={6}>
            <DBEntityButton
              Icon={<IconSquareRoundedPlus size="2.375rem" />}
              metadata={SupplyMetadata}
              height={HEIGHT_1}
              link="/accounting/supply"
            />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  );
}
