// client-react/hooks/useBreadcrumbs.tsx
import { Text } from "@mantine/core";
import { IconHome2 } from "@tabler/icons-react";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

interface Path {
  href: string;
  title: JSX.Element;
}

export const useBreadcrumbs = () => {
  const router = useRouter();
  const [breadcrumbs, setBreadcrumbs] = useState<Path[]>([
    { href: "/", title: <IconHome2 /> },
  ]);

  useEffect(() => {
    const pathWithoutQuery = router.asPath.split("?")[0];
    let pathArray = pathWithoutQuery.split("/");

    pathArray = pathArray.filter((path) => path !== "");

    let breadcrumbs = pathArray.map((path, index) => {
      const href = "/" + pathArray.slice(0, index + 1).join("/");
      return {
        href,
        title: <Text>{path.charAt(0).toUpperCase() + path.slice(1)}</Text>,
      };
    });
    breadcrumbs.unshift({ href: "/", title: <IconHome2 /> });

    setBreadcrumbs(breadcrumbs);
  }, [router.asPath]);

  return breadcrumbs;
};

// client-solid/src/hooks/useBreadcrumbs.tsx
import {
  Accessor,
  JSX,
  createEffect,
  createSignal,
  on,
  onMount,
} from "solid-js";
import { useLocation } from "solid-start";
import { IconBox } from "~/ui/components/IconBox";

interface Path {
  href: string;
  title: JSX.Element;
}

export const useBreadcrumbs = (): Accessor<Path[]> => {
  const location = useLocation();
  const home = [
    { href: "/", title: <IconBox icon="i-tabler-home-2" size="xs" /> },
  ];
  const update = () => {
    const pathWithoutQuery = location.pathname.split("?")[0];
    const pathArray = pathWithoutQuery.split("/").filter((path) => path !== "");
    const breadcrumbs = home.concat(
      pathArray.map((path, index) => ({
        href: "/" + pathArray.slice(0, index + 1).join("/"),
        title: path.charAt(0).toUpperCase() + path.slice(1),
      }))
    );
    return breadcrumbs;
  };
  const [prev, setPrev] = createSignal(location.pathname);
  const [breadcrumbs, setBreadcrumbs] = createSignal<Path[]>(update());
  createEffect(
    on(
      () => location.pathname,
      () => {
        if (prev() !== location.pathname) {
          setBreadcrumbs(update());
          setPrev(location.pathname);
        }
      }
    )
  );
  return breadcrumbs;
};
